API:
  repositories: https://api.github.com/search/repositories
  users: https://api.github.com/users/
DB:
  path: /home/aleks/Code/mycode/QA-framework/become_qa_auto.db
UI:
  driver_path: /home/aleks/Code/mycode/QA-framework/chromedriver_linux64/chromedriver
